#!/usr/bin/env bats
#
# Tests for the tidy plugin. Go tooling is faked via stub executables on PATH so
# the dispatch is exercised deterministically without installing goimports /
# golangci-lint (which the CI runner doesn't have either).

setup() {
  ROOT="$(cd "$BATS_TEST_DIRNAME/.." && pwd)"
  TOUCH="$ROOT/bin/tidy-touch.sh"
  STANDARD="$ROOT/bin/tidy-standard.sh"
  WORK="$(mktemp -d)"
  FAKEBIN="$(mktemp -d)"          # prepended to PATH; empty unless a test fills it
  export CLAUDE_TIDY_LOG_DIR="$WORK/log"
}

teardown() { rm -rf "$WORK" "$FAKEBIN"; }

# A goimports stub that rewrites the file (so content changes -> "formatted").
fake_goimports() {
  printf '#!/usr/bin/env bash\n[ "$1" = "-w" ] && printf "\\n// tidied\\n" >> "$2"\n' > "$FAKEBIN/goimports"
  chmod +x "$FAKEBIN/goimports"
}

# A golangci-lint stub: two findings, one for a.go and one for another file,
# to prove the hook scopes surfaced findings to the touched file.
fake_golangci() {
  {
    printf '#!/usr/bin/env bash\n'
    printf 'echo "a.go:3:6: exported function Foo should have comment (revive)"\n'
    printf 'echo "other.go:1:1: unrelated finding (govet)"\n'
  } > "$FAKEBIN/golangci-lint"
  chmod +x "$FAKEBIN/golangci-lint"
}

# Feed tidy-touch a PostToolUse payload for $1; echo additionalContext or "".
run_touch() {
  local json
  json="$(jq -nc --arg p "$1" '{tool_name:"Write", tool_input:{file_path:$p}}')"
  PATH="$FAKEBIN:$PATH" bash -c 'printf "%s" "$1" | "$2"' _ "$json" "$TOUCH" \
    | jq -r '.hookSpecificOutput.additionalContext // empty' 2>/dev/null || true
}

# ---- SessionStart standard --------------------------------------------------

@test "standard hook emits valid SessionStart JSON with the clean-as-you-go policy" {
  run bash -c 'printf "{}" | "$1" | jq -r .hookSpecificOutput.hookEventName' _ "$STANDARD"
  [ "$status" -eq 0 ]
  [ "$output" = "SessionStart" ]
  run bash -c 'printf "{}" | "$1" | jq -r .hookSpecificOutput.additionalContext' _ "$STANDARD"
  [[ "$output" == *"Clean-as-you-go"* ]]
  [[ "$output" == *"scope of your change"* ]]
}

# ---- no-op paths ------------------------------------------------------------

@test "an unsupported file type is left untouched (silent)" {
  printf 'hello\n' > "$WORK/notes.txt"
  run run_touch "$WORK/notes.txt"
  [ -z "$output" ]
}

@test "a Go file is a silent no-op when no Go tooling is installed" {
  printf 'package x\n' > "$WORK/a.go"   # FAKEBIN empty -> goimports/golangci-lint absent
  run run_touch "$WORK/a.go"
  [ -z "$output" ]
}

@test "a missing file path is ignored" {
  run run_touch "$WORK/does-not-exist.go"
  [ -z "$output" ]
}

# ---- Go format + lint -------------------------------------------------------

@test "a Go file is auto-formatted and the model is told to re-read it" {
  fake_goimports
  printf 'package x\nfunc Foo(){}\n' > "$WORK/a.go"
  run run_touch "$WORK/a.go"
  [[ "$output" == *"auto-formatted"* ]]
  [[ "$output" == *"re-read"* ]]
  grep -q '// tidied' "$WORK/a.go"          # the formatter actually ran
}

@test "linter findings are surfaced, scoped to the touched file" {
  fake_goimports
  fake_golangci
  printf 'package x\nfunc Foo(){}\n' > "$WORK/a.go"
  run run_touch "$WORK/a.go"
  [[ "$output" == *"exported function Foo should have comment"* ]]
  [[ "$output" != *"unrelated finding"* ]]   # other.go finding filtered out
}

@test "generated Go files are skipped even when tooling is present" {
  fake_goimports
  fake_golangci
  printf '// Code generated by protoc. DO NOT EDIT.\npackage x\n' > "$WORK/gen.go"
  before="$(cksum "$WORK/gen.go")"
  run run_touch "$WORK/gen.go"
  [ -z "$output" ]                            # silent
  [ "$(cksum "$WORK/gen.go")" = "$before" ]   # and untouched
}
